#!/usr/bin/env bash
# Build the baseline-policy brain wasm:
#   build/moba_brain.wasm  (sim/brain_shim.c + vendored puffernet.h
#                           + embedded vendor/upstream/moba_weights.bin)
#
# The weights are embedded as a generated C array (xxd -i at build time,
# written under build/, never committed) so the wasm needs no filesystem.
# Same STANDALONE_WASM reactor flags as sim/build_sim.sh; the brain needs
# only ~5 MB so the 1 GB ceiling is just flag parity with the sim build.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

if ! command -v emcc >/dev/null 2>&1; then
    echo "error: emcc not found on PATH - install emscripten (brew install emscripten)" >&2
    exit 1
fi

mkdir -p build

WEIGHTS=vendor/upstream/moba_weights.bin
EMBED=build/moba_weights_embedded.c
{
    printf '// generated by sim/build_brain.sh from %s - do not edit\n' "$WEIGHTS"
    printf 'const unsigned char moba_weights_bin[] = {\n'
    xxd -i < "$WEIGHTS"
    printf '};\nconst unsigned int moba_weights_bin_len = sizeof(moba_weights_bin);\n'
} > "$EMBED"

COMMON_FLAGS=(-O2 -sSTANDALONE_WASM --no-entry
              -sALLOW_MEMORY_GROWTH=1 -sMAXIMUM_MEMORY=1gb -sABORTING_MALLOC=1)

emcc "${COMMON_FLAGS[@]}" -I vendor/upstream sim/brain_shim.c "$EMBED" \
    -o build/moba_brain.wasm

ls -la build/moba_brain.wasm
echo "build_brain: OK"
